#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MinionLib.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CardComponentRegisterSourceGenerator : IIncrementalGenerator
{
    private const string CardComponentInterfaceMetadataName = "MinionLib.Component.Interfaces.ICardComponent";
    private const string CardComponentMetadataName = "MinionLib.Component.CardComponent";

    private static readonly DiagnosticDescriptor ComponentTypeMustBePartial = new(
        id: "MLSG206",
        title: "ICardComponent implementation must be partial",
        messageFormat: "Type '{0}' implements ICardComponent and must be declared partial for generated registration code",
        category: "MinionLib.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetCandidate(ctx))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value)
            .Collect()
            .Select(static (items, _) => new EquatableArray<ComponentTypeData>(items));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static ComponentTypeData? GetCandidate(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        var declaredSymbol = context.SemanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
        if (declaredSymbol == null)
            return null;

        var type = declaredSymbol;

        if (type.TypeKind != TypeKind.Class || type.IsAbstract)
            return null;

        var iCardComponentSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName(CardComponentInterfaceMetadataName);
        if (iCardComponentSymbol == null)
            return null;

        if (!ImplementsInterface(type, iCardComponentSymbol))
            return null;

        var cardComponentSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName(CardComponentMetadataName);
        var isCardComponentSubtype = cardComponentSymbol != null && InheritsFrom(type, cardComponentSymbol);

        var needsGeneratedComponentId = isCardComponentSubtype && NeedsGeneratedComponentId(type, iCardComponentSymbol);

        return new ComponentTypeData(
            HintName: BuildHintName(type),
            NamespaceName: type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
            ContainingTypes: BuildContainingTypeChain(type),
            TypeDisplayName: GetTypeDisplayName(type),
            FullyQualifiedTypeName: type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsTypePartial: IsFullyPartial(type),
            TypeLocation: GetSourceLocation(type),
            DefaultComponentId: BuildDefaultComponentId(type),
            RequiresGeneratedComponentId: needsGeneratedComponentId);
    }

    private static void Emit(SourceProductionContext context, EquatableArray<ComponentTypeData> items)
    {
        foreach (var typeData in items.Items.OrderBy(static x => x.TypeDisplayName, StringComparer.Ordinal))
        {
            if (!typeData.IsTypePartial)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ComponentTypeMustBePartial,
                    typeData.TypeLocation,
                    typeData.TypeDisplayName));
                continue;
            }

            var source = BuildSource(typeData);
            context.AddSource(typeData.HintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(ComponentTypeData typeData)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS0618");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrWhiteSpace(typeData.NamespaceName))
        {
            sb.Append("namespace ").Append(typeData.NamespaceName).AppendLine(";");
            sb.AppendLine();
        }

        AppendContainingTypeDeclarations(sb, typeData.ContainingTypes);

        if (typeData.RequiresGeneratedComponentId)
        {
            sb.AppendLine("    public override string ComponentId => \"" + EscapeForStringLiteral(typeData.DefaultComponentId) + "\";");
            sb.AppendLine();
        }

        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void __AutoRegister_Component()");
        sb.AppendLine("    {");
        sb.Append("        global::MinionLib.Component.Core.CardComponentRegistry.Register(((global::MinionLib.Component.Interfaces.ICardComponent)new ")
            .Append(typeData.FullyQualifiedTypeName)
            .Append("()).ComponentId, typeof(")
            .Append(typeData.FullyQualifiedTypeName)
            .Append("), static () => new ")
            .Append(typeData.FullyQualifiedTypeName)
            .AppendLine("());");
        sb.AppendLine("    }");

        AppendContainingTypeClosures(sb, typeData.ContainingTypes.Length);
        return sb.ToString();
    }

    private static bool NeedsGeneratedComponentId(INamedTypeSymbol type, INamedTypeSymbol iCardComponentSymbol)
    {
        var interfaceComponentId = iCardComponentSymbol
            .GetMembers("ComponentId")
            .OfType<IPropertySymbol>()
            .FirstOrDefault();

        if (interfaceComponentId == null)
            return false;

        var impl = type.FindImplementationForInterfaceMember(interfaceComponentId) as IPropertySymbol;
        if (impl == null)
            return false;

        // If the class already provides a concrete implementation (directly or inherited), do not generate.
        if (!impl.IsAbstract)
            return false;

        return true;
    }

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
    {
        return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol));
    }

    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var current = type; current != null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
        }

        return false;
    }

    private static string BuildDefaultComponentId(INamedTypeSymbol type)
    {
        var rootNamespace = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();
        if (string.IsNullOrWhiteSpace(rootNamespace))
            return type.Name;

        var splitIndex = rootNamespace.IndexOf('.');
        if (splitIndex < 0)
            splitIndex = rootNamespace.Length;

        return rootNamespace.Substring(0, splitIndex) + "." + type.Name;
    }

    private static string EscapeForStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static Location? GetSourceLocation(ISymbol symbol)
    {
        return symbol.Locations.FirstOrDefault(static l => l != null && l.IsInSource);
    }

    private static ImmutableArray<ContainingTypeData> BuildContainingTypeChain(INamedTypeSymbol containingType)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var current = containingType; current != null; current = current.ContainingType)
            stack.Push(current);

        var builder = ImmutableArray.CreateBuilder<ContainingTypeData>(stack.Count);
        while (stack.Count > 0)
        {
            var type = stack.Pop();
            builder.Add(new ContainingTypeData(
                GetTypeKeyword(type),
                type.Name,
                type.TypeParameters.Select(static x => x.Name).ToImmutableArray()));
        }

        return builder.ToImmutable();
    }

    private static bool IsFullyPartial(INamedTypeSymbol type)
    {
        for (var current = type; current != null; current = current.ContainingType)
        {
            if (!IsPartial(current))
                return false;
        }

        return true;
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences
            .Select(static r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(static s => s.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));
    }

    private static string BuildHintName(INamedTypeSymbol type)
    {
        var containingType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('.', '_');

        return containingType + ".ComponentRegister.g.cs";
    }

    private static string GetTypeDisplayName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
    }

    private static string GetTypeKeyword(INamedTypeSymbol symbol)
    {
        if (symbol.IsStatic)
            return "static class";

        if (symbol.IsRecord)
            return symbol.IsValueType ? "record struct" : "record";

        return symbol.TypeKind switch
        {
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class"
        };
    }

    private static void AppendContainingTypeDeclarations(StringBuilder builder, ImmutableArray<ContainingTypeData> containingTypes)
    {
        for (var i = 0; i < containingTypes.Length; i++)
        {
            var type = containingTypes[i];
            var indent = new string(' ', i * 4);
            builder.Append(indent)
                .Append("partial ")
                .Append(type.Keyword)
                .Append(' ')
                .Append(type.Name);

            if (!type.TypeParameters.IsDefaultOrEmpty)
                builder.Append('<').Append(string.Join(", ", type.TypeParameters)).Append('>');

            builder.AppendLine();
            builder.Append(indent).AppendLine("{");
        }
    }

    private static void AppendContainingTypeClosures(StringBuilder builder, int depth)
    {
        for (var i = depth - 1; i >= 0; i--)
            builder.Append(new string(' ', i * 4)).AppendLine("}");
    }

    private readonly record struct ComponentTypeData(
        string HintName,
        string? NamespaceName,
        ImmutableArray<ContainingTypeData> ContainingTypes,
        string TypeDisplayName,
        string FullyQualifiedTypeName,
        bool IsTypePartial,
        Location? TypeLocation,
        string DefaultComponentId,
        bool RequiresGeneratedComponentId);

    private readonly record struct ContainingTypeData(
        string Keyword,
        string Name,
        ImmutableArray<string> TypeParameters);
}


