// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
#nullable enable

using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.CardRewardAlternatives;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.RestSite;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.ValueProps;

namespace MinionLib.Component;

public abstract partial class CardComponent
{
  public virtual int ModifyAttackHitCount(AttackCommand attack, int hitCount) => hitCount;

  public virtual Decimal ModifyBlockAdditive(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 0M;
  }

  public virtual Decimal ModifyBlockMultiplicative(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 1M;
  }

  public virtual int ModifyCardPlayCount(CardModel card, Creature? target, int playCount)
  {
    return playCount;
  }

  public virtual (PileType, CardPilePosition) ModifyCardPlayResultPileTypeAndPosition(
    CardModel card,
    bool isAutoPlay,
    ResourceInfo resources,
    PileType pileType,
    CardPilePosition position)
  {
    return (pileType, position);
  }

  public virtual int ModifyOrbPassiveTriggerCounts(OrbModel orb, int triggerCount) => triggerCount;

  public virtual CardCreationOptions ModifyCardRewardCreationOptions(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  public virtual CardCreationOptions ModifyCardRewardCreationOptionsLate(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  public virtual Decimal ModifyCardRewardUpgradeOdds(Player player, CardModel card, Decimal odds)
  {
    return odds;
  }

  public virtual Decimal ModifyDamageAdditive(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 0M;
  }

  public virtual Decimal ModifyDamageCap(
    Creature? target,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return Decimal.MaxValue;
  }

  public virtual Decimal ModifyDamageMultiplicative(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 1M;
  }

  public virtual Decimal ModifyEnergyGain(Player player, Decimal amount) => amount;

  public virtual ActMap ModifyGeneratedMap(IRunState runState, ActMap map, int actIndex) => map;

  public virtual ActMap ModifyGeneratedMapLate(IRunState runState, ActMap map, int actIndex) => map;

  public virtual Decimal ModifyHandDraw(Player player, Decimal count) => count;

  public virtual Decimal ModifyHandDrawLate(Player player, Decimal count) => count;

  public virtual Decimal ModifyHpLostBeforeOsty(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  public virtual Decimal ModifyHpLostBeforeOstyLate(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  public virtual Decimal ModifyHpLostAfterOsty(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  public virtual Decimal ModifyHpLostAfterOstyLate(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  public virtual Decimal ModifyMaxEnergy(Player player, Decimal amount) => amount;

  public virtual IEnumerable<CardModel> ModifyMerchantCardPool(
    Player player,
    IEnumerable<CardModel> options)
  {
    return options;
  }

  public virtual CardRarity ModifyMerchantCardRarity(Player player, CardRarity rarity) => rarity;

  public virtual void ModifyMerchantCardCreationResults(
    Player player,
    List<CardCreationResult> cards)
  {
  }

  public virtual Decimal ModifyMerchantPrice(Player player, MerchantEntry entry, Decimal cost)
  {
    return cost;
  }

  public virtual Decimal ModifyOrbValue(Player player, Decimal value) => value;

  public virtual Decimal ModifyPowerAmountGiven(
    PowerModel power,
    Creature giver,
    Decimal amount,
    Creature? target,
    CardModel? cardSource)
  {
    return amount;
  }

  public virtual Decimal ModifyRestSiteHealAmount(Creature creature, Decimal amount) => amount;

  public virtual void ModifyShuffleOrder(
    Player player,
    List<CardModel> cards,
    bool isInitialShuffle)
  {
  }

  public virtual Decimal ModifySummonAmount(Player summoner, Decimal amount, AbstractModel? source)
  {
    return amount;
  }

  public virtual Creature ModifyUnblockedDamageTarget(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer)
  {
    return target;
  }

  public virtual EventModel ModifyNextEvent(EventModel currentEvent) => currentEvent;

  public virtual IReadOnlySet<RoomType> ModifyUnknownMapPointRoomTypes(
    IReadOnlySet<RoomType> roomTypes)
  {
    return roomTypes;
  }

  public virtual float ModifyOddsIncreaseForUnrolledRoomType(RoomType roomType, float oddsIncrease)
  {
    return oddsIncrease;
  }

  public virtual int ModifyXValue(CardModel card, int originalValue) => originalValue;

  public virtual bool TryModifyCardBeingAddedToDeck(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  public virtual bool TryModifyCardBeingAddedToDeckLate(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  public virtual bool TryModifyCardRewardAlternatives(
    Player player,
    CardReward cardReward,
    List<CardRewardAlternative> alternatives)
  {
    return false;
  }

  public virtual bool TryModifyCardRewardOptions(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  public virtual bool TryModifyCardRewardOptionsLate(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  public virtual bool TryModifyEnergyCostInCombat(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  public virtual bool TryModifyStarCost(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  public virtual bool TryModifyPowerAmountReceived(
    PowerModel canonicalPower,
    Creature target,
    Decimal amount,
    Creature? applier,
    out Decimal modifiedAmount)
  {
    modifiedAmount = amount;
    return false;
  }

  public virtual bool TryModifyRestSiteOptions(Player player, ICollection<RestSiteOption> options)
  {
    return false;
  }

  public virtual bool TryModifyRestSiteHealRewards(
    Player player,
    List<Reward> rewards,
    bool isMimicked)
  {
    return false;
  }

  public virtual bool TryModifyRewards(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  public virtual bool TryModifyRewardsLate(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  public virtual IReadOnlyList<LocString> ModifyExtraRestSiteHealText(
    Player player,
    IReadOnlyList<LocString> currentExtraText)
  {
    return currentExtraText;
  }
}