// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

using System.Buffers;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
using MinionLib.Component.Interfaces;
using System.ComponentModel;
using MegaCrit.Sts2.Core.Entities.CardRewardAlternatives;
using MegaCrit.Sts2.Core.Entities.RestSite;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Runs;

namespace MinionLib.Component;

#pragma warning disable CS0809
public abstract partial class ComponentsCardModel
{
  protected virtual int ModifyAttackHitCountC(AttackCommand attack, int hitCount) => hitCount;

  protected virtual Decimal ModifyBlockAdditiveC(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 0M;
  }

  protected virtual Decimal ModifyBlockMultiplicativeC(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 1M;
  }

  protected virtual int ModifyCardPlayCountC(CardModel card, Creature? target, int playCount)
  {
    return playCount;
  }

  protected virtual (PileType, CardPilePosition) ModifyCardPlayResultPileTypeAndPositionC(
    CardModel card,
    bool isAutoPlay,
    ResourceInfo resources,
    PileType pileType,
    CardPilePosition position)
  {
    return (pileType, position);
  }

  protected virtual int ModifyOrbPassiveTriggerCountsC(OrbModel orb, int triggerCount) => triggerCount;

  protected virtual CardCreationOptions ModifyCardRewardCreationOptionsC(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  protected virtual CardCreationOptions ModifyCardRewardCreationOptionsLateC(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  protected virtual Decimal ModifyCardRewardUpgradeOddsC(Player player, CardModel card, Decimal odds)
  {
    return odds;
  }

  protected virtual Decimal ModifyDamageAdditiveC(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 0M;
  }

  protected virtual Decimal ModifyDamageCapC(
    Creature? target,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return Decimal.MaxValue;
  }

  protected virtual Decimal ModifyDamageMultiplicativeC(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 1M;
  }

  protected virtual Decimal ModifyEnergyGainC(Player player, Decimal amount) => amount;

  protected virtual ActMap ModifyGeneratedMapC(IRunState runState, ActMap map, int actIndex) => map;

  protected virtual ActMap ModifyGeneratedMapLateC(IRunState runState, ActMap map, int actIndex) => map;

  protected virtual Decimal ModifyHandDrawC(Player player, Decimal count) => count;

  protected virtual Decimal ModifyHandDrawLateC(Player player, Decimal count) => count;

  protected virtual Decimal ModifyHpLostBeforeOstyC(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  protected virtual Decimal ModifyHpLostBeforeOstyLateC(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  protected virtual Decimal ModifyHpLostAfterOstyC(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  protected virtual Decimal ModifyHpLostAfterOstyLateC(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  protected virtual Decimal ModifyMaxEnergyC(Player player, Decimal amount) => amount;

  protected virtual IEnumerable<CardModel> ModifyMerchantCardPoolC(
    Player player,
    IEnumerable<CardModel> options)
  {
    return options;
  }

  protected virtual CardRarity ModifyMerchantCardRarityC(Player player, CardRarity rarity) => rarity;

  protected virtual void ModifyMerchantCardCreationResultsC(
    Player player,
    List<CardCreationResult> cards)
  {
  }

  protected virtual Decimal ModifyMerchantPriceC(Player player, MerchantEntry entry, Decimal cost)
  {
    return cost;
  }

  protected virtual Decimal ModifyOrbValueC(Player player, Decimal value) => value;

  protected virtual Decimal ModifyPowerAmountGivenC(
    PowerModel power,
    Creature giver,
    Decimal amount,
    Creature? target,
    CardModel? cardSource)
  {
    return amount;
  }

  protected virtual Decimal ModifyRestSiteHealAmountC(Creature creature, Decimal amount) => amount;

  protected virtual void ModifyShuffleOrderC(
    Player player,
    List<CardModel> cards,
    bool isInitialShuffle)
  {
  }

  protected virtual Decimal ModifySummonAmountC(Player summoner, Decimal amount, AbstractModel? source)
  {
    return amount;
  }

  protected virtual Creature ModifyUnblockedDamageTargetC(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer)
  {
    return target;
  }

  protected virtual EventModel ModifyNextEventC(EventModel currentEvent) => currentEvent;

  protected virtual IReadOnlySet<RoomType> ModifyUnknownMapPointRoomTypesC(
    IReadOnlySet<RoomType> roomTypes)
  {
    return roomTypes;
  }

  protected virtual float ModifyOddsIncreaseForUnrolledRoomTypeC(RoomType roomType, float oddsIncrease)
  {
    return oddsIncrease;
  }

  protected virtual int ModifyXValueC(CardModel card, int originalValue) => originalValue;

  protected virtual bool TryModifyCardBeingAddedToDeckC(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  protected virtual bool TryModifyCardBeingAddedToDeckLateC(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  protected virtual bool TryModifyCardRewardAlternativesC(
    Player player,
    CardReward cardReward,
    List<CardRewardAlternative> alternatives)
  {
    return false;
  }

  protected virtual bool TryModifyCardRewardOptionsC(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  protected virtual bool TryModifyCardRewardOptionsLateC(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  protected virtual bool TryModifyEnergyCostInCombatC(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  protected virtual bool TryModifyStarCostC(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  protected virtual bool TryModifyPowerAmountReceivedC(
    PowerModel canonicalPower,
    Creature target,
    Decimal amount,
    Creature? applier,
    out Decimal modifiedAmount)
  {
    modifiedAmount = amount;
    return false;
  }

  protected virtual bool TryModifyRestSiteOptionsC(Player player, ICollection<RestSiteOption> options)
  {
    return false;
  }

  protected virtual bool TryModifyRestSiteHealRewardsC(
    Player player,
    List<Reward> rewards,
    bool isMimicked)
  {
    return false;
  }

  protected virtual bool TryModifyRewardsC(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  protected virtual bool TryModifyRewardsLateC(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  protected virtual IReadOnlyList<LocString> ModifyExtraRestSiteHealTextC(
    Player player,
    IReadOnlyList<LocString> currentExtraText)
  {
    return currentExtraText;
  }

}