// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

using System.Buffers;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.CardRewardAlternatives;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.RestSite;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
using MinionLib.Component.Interfaces;
using System.ComponentModel;

namespace MinionLib.Component;

#pragma warning disable CS0809
public abstract partial class ComponentsCardModel
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override int ModifyAttackHitCount(AttackCommand attack, int hitCount)
    {
        EnsureComponentsInitialized();
        var result = hitCount;
        foreach (var component in _components!)
            result = component.ModifyAttackHitCount(attack, result);
        return ModifyAttackHitCountC(attack, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyBlockAdditive(Creature target, Decimal block, ValueProp props, CardModel? cardSource, CardPlay? cardPlay)
    {
        EnsureComponentsInitialized();
        var result = block;
        foreach (var component in _components!)
            result = component.ModifyBlockAdditive(target, result, props, cardSource, cardPlay);
        return ModifyBlockAdditiveC(target, result, props, cardSource, cardPlay);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyBlockMultiplicative(Creature target, Decimal block, ValueProp props, CardModel? cardSource, CardPlay? cardPlay)
    {
        EnsureComponentsInitialized();
        var result = block;
        foreach (var component in _components!)
            result = component.ModifyBlockMultiplicative(target, result, props, cardSource, cardPlay);
        return ModifyBlockMultiplicativeC(target, result, props, cardSource, cardPlay);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override int ModifyCardPlayCount(CardModel card, Creature? target, int playCount)
    {
        EnsureComponentsInitialized();
        var result = playCount;
        foreach (var component in _components!)
            result = component.ModifyCardPlayCount(card, target, result);
        return ModifyCardPlayCountC(card, target, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override (PileType, CardPilePosition) ModifyCardPlayResultPileTypeAndPosition(CardModel card, bool isAutoPlay, ResourceInfo resources, PileType pileType, CardPilePosition position)
    {
        EnsureComponentsInitialized();
        var result = (pileType, position);
        foreach (var component in _components!)
            result = component.ModifyCardPlayResultPileTypeAndPosition(card, isAutoPlay, resources, result.Item1, result.Item2);
        return ModifyCardPlayResultPileTypeAndPositionC(card, isAutoPlay, resources, result.Item1, result.Item2);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override int ModifyOrbPassiveTriggerCounts(OrbModel orb, int triggerCount)
    {
        EnsureComponentsInitialized();
        var result = triggerCount;
        foreach (var component in _components!)
            result = component.ModifyOrbPassiveTriggerCounts(orb, result);
        return ModifyOrbPassiveTriggerCountsC(orb, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override CardCreationOptions ModifyCardRewardCreationOptions(Player player, CardCreationOptions options)
    {
        EnsureComponentsInitialized();
        var result = options;
        foreach (var component in _components!)
            result = component.ModifyCardRewardCreationOptions(player, result);
        return ModifyCardRewardCreationOptionsC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override CardCreationOptions ModifyCardRewardCreationOptionsLate(Player player, CardCreationOptions options)
    {
        EnsureComponentsInitialized();
        var result = options;
        foreach (var component in _components!)
            result = component.ModifyCardRewardCreationOptionsLate(player, result);
        return ModifyCardRewardCreationOptionsLateC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyCardRewardUpgradeOdds(Player player, CardModel card, Decimal odds)
    {
        EnsureComponentsInitialized();
        var result = odds;
        foreach (var component in _components!)
            result = component.ModifyCardRewardUpgradeOdds(player, card, result);
        return ModifyCardRewardUpgradeOddsC(player, card, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyDamageAdditive(Creature? target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyDamageAdditive(target, result, props, dealer, cardSource);
        return ModifyDamageAdditiveC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyDamageCap(Creature? target, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = Decimal.MaxValue;
        foreach (var component in _components!)
            result = component.ModifyDamageCap(target, props, dealer, cardSource);
        return ModifyDamageCapC(target, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyDamageMultiplicative(Creature? target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyDamageMultiplicative(target, result, props, dealer, cardSource);
        return ModifyDamageMultiplicativeC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyEnergyGain(Player player, Decimal amount)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyEnergyGain(player, result);
        return ModifyEnergyGainC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override ActMap ModifyGeneratedMap(IRunState runState, ActMap map, int actIndex)
    {
        EnsureComponentsInitialized();
        var result = map;
        foreach (var component in _components!)
            result = component.ModifyGeneratedMap(runState, result, actIndex);
        return ModifyGeneratedMapC(runState, result, actIndex);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override ActMap ModifyGeneratedMapLate(IRunState runState, ActMap map, int actIndex)
    {
        EnsureComponentsInitialized();
        var result = map;
        foreach (var component in _components!)
            result = component.ModifyGeneratedMapLate(runState, result, actIndex);
        return ModifyGeneratedMapLateC(runState, result, actIndex);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHandDraw(Player player, Decimal count)
    {
        EnsureComponentsInitialized();
        var result = count;
        foreach (var component in _components!)
            result = component.ModifyHandDraw(player, result);
        return ModifyHandDrawC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHandDrawLate(Player player, Decimal count)
    {
        EnsureComponentsInitialized();
        var result = count;
        foreach (var component in _components!)
            result = component.ModifyHandDrawLate(player, result);
        return ModifyHandDrawLateC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHpLostBeforeOsty(Creature target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyHpLostBeforeOsty(target, result, props, dealer, cardSource);
        return ModifyHpLostBeforeOstyC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHpLostBeforeOstyLate(Creature target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyHpLostBeforeOstyLate(target, result, props, dealer, cardSource);
        return ModifyHpLostBeforeOstyLateC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHpLostAfterOsty(Creature target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyHpLostAfterOsty(target, result, props, dealer, cardSource);
        return ModifyHpLostAfterOstyC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyHpLostAfterOstyLate(Creature target, Decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyHpLostAfterOstyLate(target, result, props, dealer, cardSource);
        return ModifyHpLostAfterOstyLateC(target, result, props, dealer, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyMaxEnergy(Player player, Decimal amount)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyMaxEnergy(player, result);
        return ModifyMaxEnergyC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override IEnumerable<CardModel> ModifyMerchantCardPool(Player player, IEnumerable<CardModel> options)
    {
        EnsureComponentsInitialized();
        var result = options;
        foreach (var component in _components!)
            result = component.ModifyMerchantCardPool(player, result);
        return ModifyMerchantCardPoolC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override CardRarity ModifyMerchantCardRarity(Player player, CardRarity rarity)
    {
        EnsureComponentsInitialized();
        var result = rarity;
        foreach (var component in _components!)
            result = component.ModifyMerchantCardRarity(player, result);
        return ModifyMerchantCardRarityC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override void ModifyMerchantCardCreationResults(Player player, List<CardCreationResult> cards)
    {
        EnsureComponentsInitialized();
        foreach (var component in _components!)
            component.ModifyMerchantCardCreationResults(player, cards);
        ModifyMerchantCardCreationResultsC(player, cards);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyMerchantPrice(Player player, MerchantEntry entry, Decimal cost)
    {
        EnsureComponentsInitialized();
        var result = cost;
        foreach (var component in _components!)
            result = component.ModifyMerchantPrice(player, entry, result);
        return ModifyMerchantPriceC(player, entry, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyOrbValue(Player player, Decimal value)
    {
        EnsureComponentsInitialized();
        var result = value;
        foreach (var component in _components!)
            result = component.ModifyOrbValue(player, result);
        return ModifyOrbValueC(player, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyPowerAmountGiven(PowerModel power, Creature giver, Decimal amount, Creature? target, CardModel? cardSource)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyPowerAmountGiven(power, giver, result, target, cardSource);
        return ModifyPowerAmountGivenC(power, giver, result, target, cardSource);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifyRestSiteHealAmount(Creature creature, Decimal amount)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifyRestSiteHealAmount(creature, result);
        return ModifyRestSiteHealAmountC(creature, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override void ModifyShuffleOrder(Player player, List<CardModel> cards, bool isInitialShuffle)
    {
        EnsureComponentsInitialized();
        foreach (var component in _components!)
            component.ModifyShuffleOrder(player, cards, isInitialShuffle);
        ModifyShuffleOrderC(player, cards, isInitialShuffle);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Decimal ModifySummonAmount(Player summoner, Decimal amount, AbstractModel? source)
    {
        EnsureComponentsInitialized();
        var result = amount;
        foreach (var component in _components!)
            result = component.ModifySummonAmount(summoner, result, source);
        return ModifySummonAmountC(summoner, result, source);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override Creature ModifyUnblockedDamageTarget(Creature target, Decimal amount, ValueProp props, Creature? dealer)
    {
        EnsureComponentsInitialized();
        var result = target;
        foreach (var component in _components!)
            result = component.ModifyUnblockedDamageTarget(result, amount, props, dealer);
        return ModifyUnblockedDamageTargetC(result, amount, props, dealer);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override EventModel ModifyNextEvent(EventModel currentEvent)
    {
        EnsureComponentsInitialized();
        var result = currentEvent;
        foreach (var component in _components!)
            result = component.ModifyNextEvent(result);
        return ModifyNextEventC(result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override IReadOnlySet<RoomType> ModifyUnknownMapPointRoomTypes(IReadOnlySet<RoomType> roomTypes)
    {
        EnsureComponentsInitialized();
        var result = roomTypes;
        foreach (var component in _components!)
            result = component.ModifyUnknownMapPointRoomTypes(result);
        return ModifyUnknownMapPointRoomTypesC(result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override float ModifyOddsIncreaseForUnrolledRoomType(RoomType roomType, float oddsIncrease)
    {
        EnsureComponentsInitialized();
        var result = oddsIncrease;
        foreach (var component in _components!)
            result = component.ModifyOddsIncreaseForUnrolledRoomType(roomType, result);
        return ModifyOddsIncreaseForUnrolledRoomTypeC(roomType, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override int ModifyXValue(CardModel card, int originalValue)
    {
        EnsureComponentsInitialized();
        var result = originalValue;
        foreach (var component in _components!)
            result = component.ModifyXValue(card, result);
        return ModifyXValueC(card, result);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyCardBeingAddedToDeck(CardModel card, out CardModel? newCard)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
        {
            if (component.TryModifyCardBeingAddedToDeck(card, out var modified) && modified != null)
            {
                flag = true;
                card = modified;
            }
        }
        if (TryModifyCardBeingAddedToDeckC(card, out var modifiedC) && modifiedC != null)
        {
            flag = true;
            card = modifiedC;
        }
        newCard = flag ? card : null;
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyCardBeingAddedToDeckLate(CardModel card, out CardModel? newCard)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
        {
            if (component.TryModifyCardBeingAddedToDeckLate(card, out var modified) && modified != null)
            {
                flag = true;
                card = modified;
            }
        }
        if (TryModifyCardBeingAddedToDeckLateC(card, out var modifiedC) && modifiedC != null)
        {
            flag = true;
            card = modifiedC;
        }
        newCard = flag ? card : null;
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyCardRewardAlternatives(Player player, CardReward cardReward, List<CardRewardAlternative> alternatives)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyCardRewardAlternatives(player, cardReward, alternatives);
        flag |= TryModifyCardRewardAlternativesC(player, cardReward, alternatives);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyCardRewardOptions(Player player, List<CardCreationResult> cardRewardOptions, CardCreationOptions creationOptions)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyCardRewardOptions(player, cardRewardOptions, creationOptions);
        flag |= TryModifyCardRewardOptionsC(player, cardRewardOptions, creationOptions);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyCardRewardOptionsLate(Player player, List<CardCreationResult> cardRewardOptions, CardCreationOptions creationOptions)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyCardRewardOptionsLate(player, cardRewardOptions, creationOptions);
        flag |= TryModifyCardRewardOptionsLateC(player, cardRewardOptions, creationOptions);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyEnergyCostInCombat(CardModel card, Decimal originalCost, out Decimal modifiedCost)
    {
        EnsureComponentsInitialized();
        var flag = false;
        var currentCost = originalCost;
        foreach (var component in _components!)
        {
            if (component.TryModifyEnergyCostInCombat(card, currentCost, out var modified))
            {
                flag = true;
                currentCost = modified;
            }
        }
        if (TryModifyEnergyCostInCombatC(card, currentCost, out var modifiedC))
        {
            flag = true;
            currentCost = modifiedC;
        }
        modifiedCost = flag ? currentCost : originalCost;
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyStarCost(CardModel card, Decimal originalCost, out Decimal modifiedCost)
    {
        EnsureComponentsInitialized();
        var flag = false;
        var currentCost = originalCost;
        foreach (var component in _components!)
        {
            if (component.TryModifyStarCost(card, currentCost, out var modified))
            {
                flag = true;
                currentCost = modified;
            }
        }
        if (TryModifyStarCostC(card, currentCost, out var modifiedC))
        {
            flag = true;
            currentCost = modifiedC;
        }
        modifiedCost = flag ? currentCost : originalCost;
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyPowerAmountReceived(PowerModel canonicalPower, Creature target, Decimal amount, Creature? applier, out Decimal modifiedAmount)
    {
        EnsureComponentsInitialized();
        var flag = false;
        var currentAmount = amount;
        foreach (var component in _components!)
        {
            if (component.TryModifyPowerAmountReceived(canonicalPower, target, currentAmount, applier, out var modified))
            {
                flag = true;
                currentAmount = modified;
            }
        }
        if (TryModifyPowerAmountReceivedC(canonicalPower, target, currentAmount, applier, out var modifiedC))
        {
            flag = true;
            currentAmount = modifiedC;
        }
        modifiedAmount = flag ? currentAmount : amount;
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyRestSiteOptions(Player player, ICollection<RestSiteOption> options)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyRestSiteOptions(player, options);
        flag |= TryModifyRestSiteOptionsC(player, options);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyRestSiteHealRewards(Player player, List<Reward> rewards, bool isMimicked)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyRestSiteHealRewards(player, rewards, isMimicked);
        flag |= TryModifyRestSiteHealRewardsC(player, rewards, isMimicked);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyRewards(Player player, List<Reward> rewards, AbstractRoom? room)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyRewards(player, rewards, room);
        flag |= TryModifyRewardsC(player, rewards, room);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override bool TryModifyRewardsLate(Player player, List<Reward> rewards, AbstractRoom? room)
    {
        EnsureComponentsInitialized();
        var flag = false;
        foreach (var component in _components!)
            flag |= component.TryModifyRewardsLate(player, rewards, room);
        flag |= TryModifyRewardsLateC(player, rewards, room);
        return flag;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try using the C-ending one instead, or disable this warning if intended.", false)]
    public sealed override IReadOnlyList<LocString> ModifyExtraRestSiteHealText(Player player, IReadOnlyList<LocString> currentExtraText)
    {
        EnsureComponentsInitialized();
        var result = currentExtraText;
        foreach (var component in _components!)
            result = component.ModifyExtraRestSiteHealText(player, result);
        return ModifyExtraRestSiteHealTextC(player, result);
    }

}