// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;

namespace MinionLib.Component.Interfaces;

public partial interface ICardComponent
{
    Task OnPlayPrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task OnPlayPostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task OnEnqueuePlayVfxPrefix(Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task OnEnqueuePlayVfxPostfix(Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task OnTurnEndInHandPrefix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task OnTurnEndInHandPostfix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardPlayedPrefix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardPlayedPostfix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardPlayedPrefix(PlayerChoiceContext context, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardPlayedPostfix(PlayerChoiceContext context, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardPlayedLatePrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardPlayedLatePostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterActEnteredPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterActEnteredPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterAddToDeckPreventedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterAddToDeckPreventedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeAttackPrefix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeAttackPostfix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterAttackPrefix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterAttackPostfix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockClearedPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockClearedPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockBrokenPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterBlockBrokenPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardChangedPilesPrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardChangedPilesPostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardChangedPilesLatePrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardChangedPilesLatePostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDiscardedPrefix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDiscardedPostfix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDrawnEarlyPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDrawnEarlyPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDrawnPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardDrawnPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardEnteredCombatPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardEnteredCombatPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardGeneratedForCombatPrefix(CardModel card, bool addedByPlayer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardGeneratedForCombatPostfix(CardModel card, bool addedByPlayer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardExhaustedPrefix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardExhaustedPostfix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardAutoPlayedPrefix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardAutoPlayedPostfix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardRetainedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCardRetainedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCombatStartPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCombatStartPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCombatStartLatePrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCombatStartLatePostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatEndPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatEndPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatVictoryEarlyPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatVictoryEarlyPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatVictoryPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCombatVictoryPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCreatureAddedToCombatPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCreatureAddedToCombatPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCurrentHpChangedPrefix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterCurrentHpChangedPostfix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageGivenPrefix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageGivenPostfix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageReceivedLatePrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDamageReceivedLatePostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDeathPrefix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDeathPostfix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDiedToDoomPrefix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterDiedToDoomPostfix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergyResetPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergyResetPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergyResetLatePrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergyResetLatePostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergySpentPrefix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterEnergySpentPostfix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardRemovedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeCardRemovedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeFlushPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeFlushPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeFlushLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeFlushLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterGoldGainedPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterGoldGainedPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeHandDrawPrefix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeHandDrawPostfix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeHandDrawLatePrefix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeHandDrawLatePostfix(Player player, PlayerChoiceContext choiceContext, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterHandEmptiedPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterHandEmptiedPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterItemPurchasedPrefix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterItemPurchasedPostfix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterMapGeneratedPrefix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterMapGeneratedPostfix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingBlockAmountPrefix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingBlockAmountPostfix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardPlayCountPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardPlayCountPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardPlayResultPileOrPositionPrefix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardPlayResultPileOrPositionPostfix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingOrbPassiveTriggerCountPrefix(OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingOrbPassiveTriggerCountPostfix(OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardRewardOptionsPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingCardRewardOptionsPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingDamageAmountPrefix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingDamageAmountPostfix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingEnergyGainPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingEnergyGainPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHandDrawPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHandDrawPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingDrawPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingDrawPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHpLostBeforeOstyPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHpLostBeforeOstyPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHpLostAfterOstyPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingHpLostAfterOstyPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingPowerAmountReceivedPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingPowerAmountReceivedPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingPowerAmountGivenPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingPowerAmountGivenPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingRewardsPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterModifyingRewardsPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeRewardsOfferedPrefix(Player player, IReadOnlyList<Reward> rewards, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeRewardsOfferedPostfix(Player player, IReadOnlyList<Reward> rewards, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOrbChanneledPrefix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOrbChanneledPostfix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOrbEvokedPrefix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOrbEvokedPostfix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOstyRevivedPrefix(Creature osty, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterOstyRevivedPostfix(Creature osty, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionDiscardedPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionDiscardedPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionProcuredPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPotionProcuredPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePowerAmountChangedPrefix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePowerAmountChangedPostfix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPowerAmountChangedPrefix(PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPowerAmountChangedPostfix(PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingBlockClearPrefix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingBlockClearPostfix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPreventingDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRestSiteHealPrefix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRestSiteHealPostfix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRestSiteSmithPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRestSiteSmithPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRewardTakenPrefix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRewardTakenPostfix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterShufflePrefix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterShufflePostfix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterStarsSpentPrefix(int amount, Player spender, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterStarsSpentPostfix(int amount, Player spender, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterStarsGainedPrefix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterStarsGainedPostfix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterForgePrefix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterForgePostfix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterSummonPrefix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterSummonPostfix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTakingExtraTurnPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTakingExtraTurnPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTargetingBlockedVfxPrefix(Creature blocker, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTargetingBlockedVfxPostfix(Creature blocker, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeSideTurnStartPrefix(PlayerChoiceContext choiceContext, CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeSideTurnStartPostfix(PlayerChoiceContext choiceContext, CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterSideTurnStartPrefix(CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterSideTurnStartPostfix(CombatSide side, CombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartEarlyPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartEarlyPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterPlayerTurnStartLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePlayPhaseStartPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforePlayPhaseStartPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndVeryEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndVeryEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task BeforeTurnEndEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTurnEndLatePrefix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    Task AfterTurnEndLatePostfix(PlayerChoiceContext choiceContext, CombatSide side, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    void AfterTransformedFromPrefix(ComponentContext componentContext)
    {
    }
    
    void AfterTransformedFromPostfix(ComponentContext componentContext)
    {
    }
    
    void AfterTransformedToPrefix(ComponentContext componentContext)
    {
    }
    
    void AfterTransformedToPostfix(ComponentContext componentContext)
    {
    }
    
}
