// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.CardRewardAlternatives;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.RestSite;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;

namespace MinionLib.Component.Interfaces;

public partial interface ICardComponent
{
  int ModifyAttackHitCount(AttackCommand attack, int hitCount) => hitCount;

  Decimal ModifyBlockAdditive(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 0M;
  }

  Decimal ModifyBlockMultiplicative(
    Creature target,
    Decimal block,
    ValueProp props,
    CardModel? cardSource,
    CardPlay? cardPlay)
  {
    return 1M;
  }

  int ModifyCardPlayCount(CardModel card, Creature? target, int playCount)
  {
    return playCount;
  }

  (PileType, CardPilePosition) ModifyCardPlayResultPileTypeAndPosition(
    CardModel card,
    bool isAutoPlay,
    ResourceInfo resources,
    PileType pileType,
    CardPilePosition position)
  {
    return (pileType, position);
  }

  int ModifyOrbPassiveTriggerCounts(OrbModel orb, int triggerCount) => triggerCount;

  CardCreationOptions ModifyCardRewardCreationOptions(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  CardCreationOptions ModifyCardRewardCreationOptionsLate(
    Player player,
    CardCreationOptions options)
  {
    return options;
  }

  Decimal ModifyCardRewardUpgradeOdds(Player player, CardModel card, Decimal odds)
  {
    return odds;
  }

  Decimal ModifyDamageAdditive(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 0M;
  }

  Decimal ModifyDamageCap(
    Creature? target,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return Decimal.MaxValue;
  }

  Decimal ModifyDamageMultiplicative(
    Creature? target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return 1M;
  }

  Decimal ModifyEnergyGain(Player player, Decimal amount) => amount;

  ActMap ModifyGeneratedMap(IRunState runState, ActMap map, int actIndex) => map;

  ActMap ModifyGeneratedMapLate(IRunState runState, ActMap map, int actIndex) => map;

  Decimal ModifyHandDraw(Player player, Decimal count) => count;

  Decimal ModifyHandDrawLate(Player player, Decimal count) => count;

  Decimal ModifyHpLostBeforeOsty(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  Decimal ModifyHpLostBeforeOstyLate(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  Decimal ModifyHpLostAfterOsty(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  Decimal ModifyHpLostAfterOstyLate(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer,
    CardModel? cardSource)
  {
    return amount;
  }

  Decimal ModifyMaxEnergy(Player player, Decimal amount) => amount;

  IEnumerable<CardModel> ModifyMerchantCardPool(
    Player player,
    IEnumerable<CardModel> options)
  {
    return options;
  }

  CardRarity ModifyMerchantCardRarity(Player player, CardRarity rarity) => rarity;

  void ModifyMerchantCardCreationResults(
    Player player,
    List<CardCreationResult> cards)
  {
  }

  Decimal ModifyMerchantPrice(Player player, MerchantEntry entry, Decimal cost)
  {
    return cost;
  }

  Decimal ModifyOrbValue(Player player, Decimal value) => value;

  Decimal ModifyPowerAmountGiven(
    PowerModel power,
    Creature giver,
    Decimal amount,
    Creature? target,
    CardModel? cardSource)
  {
    return amount;
  }

  Decimal ModifyRestSiteHealAmount(Creature creature, Decimal amount) => amount;

  void ModifyShuffleOrder(
    Player player,
    List<CardModel> cards,
    bool isInitialShuffle)
  {
  }

  Decimal ModifySummonAmount(Player summoner, Decimal amount, AbstractModel? source)
  {
    return amount;
  }

  Creature ModifyUnblockedDamageTarget(
    Creature target,
    Decimal amount,
    ValueProp props,
    Creature? dealer)
  {
    return target;
  }

  EventModel ModifyNextEvent(EventModel currentEvent) => currentEvent;

  IReadOnlySet<RoomType> ModifyUnknownMapPointRoomTypes(
    IReadOnlySet<RoomType> roomTypes)
  {
    return roomTypes;
  }

  float ModifyOddsIncreaseForUnrolledRoomType(RoomType roomType, float oddsIncrease)
  {
    return oddsIncrease;
  }

  int ModifyXValue(CardModel card, int originalValue) => originalValue;

  bool TryModifyCardBeingAddedToDeck(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  bool TryModifyCardBeingAddedToDeckLate(CardModel card, out CardModel? newCard)
  {
    newCard = null;
    return false;
  }

  bool TryModifyCardRewardAlternatives(
    Player player,
    CardReward cardReward,
    List<CardRewardAlternative> alternatives)
  {
    return false;
  }

  bool TryModifyCardRewardOptions(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  bool TryModifyCardRewardOptionsLate(
    Player player,
    List<CardCreationResult> cardRewardOptions,
    CardCreationOptions creationOptions)
  {
    return false;
  }

  bool TryModifyEnergyCostInCombat(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  bool TryModifyStarCost(
    CardModel card,
    Decimal originalCost,
    out Decimal modifiedCost)
  {
    modifiedCost = originalCost;
    return false;
  }

  bool TryModifyPowerAmountReceived(
    PowerModel canonicalPower,
    Creature target,
    Decimal amount,
    Creature? applier,
    out Decimal modifiedAmount)
  {
    modifiedAmount = amount;
    return false;
  }

  bool TryModifyRestSiteOptions(Player player, ICollection<RestSiteOption> options)
  {
    return false;
  }

  bool TryModifyRestSiteHealRewards(
    Player player,
    List<Reward> rewards,
    bool isMimicked)
  {
    return false;
  }

  bool TryModifyRewards(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  bool TryModifyRewardsLate(Player player, List<Reward> rewards, AbstractRoom? room)
  {
    return false;
  }

  IReadOnlyList<LocString> ModifyExtraRestSiteHealText(
    Player player,
    IReadOnlyList<LocString> currentExtraText)
  {
    return currentExtraText;
  }
}