import re
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent.parent
COMPONENT_DIR = PROJECT_ROOT / "Component"

AUTO_GENERATED_HEADER = """\
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable

"""


class Signature(NamedTuple):
    name: str
    modifier: str
    args: str
    arg_names: str
    return_type: str
    default_impl: str


def generate_components_card(signatures: list[Signature]) -> str:
    buffer = ""
    buffer += AUTO_GENERATED_HEADER
    buffer += """\
using System.Buffers;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
using MinionLib.Component.Interfaces;
using System.ComponentModel;

namespace MinionLib.Component;

#pragma warning disable CS0809
"""
    buffer += "public abstract partial class ComponentsCardModel\n{\n"
    for signature in signatures:
        args: str
        (name, modifier, args, arg_names, return_type, default_impl) = signature
        Xxx = f"""\
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This member is sealed. Try adding `ComponentContext componentContext` as the last parameter, or disable this warning if intended.", false)]
    {modifier} sealed override {"async " if return_type == "Task" else ""}{return_type} {name}({args[:-2] if args.endswith(", ") else args})
    {{
        EnsureComponentsInitialized();

        var componentContext = new ComponentContext(ComponentPhase.Init);
        
        var count = Components.Count;
        var snapshot = ArrayPool<ICardComponent>.Shared.Rent(count);
        for (var i = 0; i < count; i++)
        {{
            snapshot[i] = Components[i];
        }}
        
        try
        {{
            for (var transitions = 0;
                 transitions < MaxPhaseTransitions && componentContext.Phase != ComponentPhase.Final;
                 transitions++)
            {{
                componentContext.MoveNextPhase();

                switch (componentContext.Phase)
                {{
                    case ComponentPhase.Prefix:
                        for(var i = 0; i < count; i++)
                        {{
                            var component = snapshot[i];
                            if (component.ComponentsCard != this) continue;
                            {"await " if return_type == "Task" else ""}component.{name}Prefix({arg_names}componentContext);
                            if (componentContext.Phase != ComponentPhase.Prefix) break;
                        }}

                        break;
                    case ComponentPhase.Postfix:
                        for(var i = count - 1; i >= 0; i--)
                        {{
                            var component = snapshot[i];
                            if(component.ComponentsCard != this) continue;
                            {"await " if return_type == "Task" else ""}component.{name}Postfix({arg_names}componentContext);
                            if (componentContext.Phase != ComponentPhase.Postfix) break;
                        }}

                        break;
                    case ComponentPhase.Prime:
                    case ComponentPhase.Core:
                    case ComponentPhase.Final:
                        {"await " if return_type == "Task" else ""}{name}Phased({arg_names}componentContext);
                        break;
                    case ComponentPhase.Init:
                    default:
                        throw new ArgumentOutOfRangeException();
                }}
            }}

            if (componentContext.Phase != ComponentPhase.Final)
                HandlePhaseTransitionLimitExceeded(componentContext.Phase);
        }}
        finally
        {{
            ArrayPool<ICardComponent>.Shared.Return(snapshot, clearArray: true);
        }}
    }}

"""
        XxxPhased = f"""\
    protected virtual {return_type} {name}Phased({args}ComponentContext componentContext)
    {{
        if (componentContext.Phase == ComponentPhase.Core)
            {"return " if return_type == "Task" else ""}{name}({arg_names}componentContext);

{default_impl}    }}

"""
        XxxNew = f"""\
    protected virtual {return_type} {name}({args}ComponentContext componentContext)
    {{
{default_impl}    }}
    
"""
        buffer += Xxx + XxxPhased + XxxNew
    buffer += "}\n"
    return buffer


def generate_i_card_component(signatures: list[Signature]) -> str:
    buffer = ""
    buffer += AUTO_GENERATED_HEADER
    buffer += """\
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;

namespace MinionLib.Component.Interfaces;

"""
    buffer += "public partial interface ICardComponent\n{\n"
    for signature in signatures:
        (name, modifier, args, arg_names, return_type, default_impl) = signature
        XxxPrefix = f"""\
    {return_type} {name}Prefix({args}ComponentContext componentContext)
    {{
{default_impl}    }}
    
"""
        XxxPostfix = f"""\
    {return_type} {name}Postfix({args}ComponentContext componentContext)
    {{
{default_impl}    }}
    
"""
        buffer += XxxPrefix + XxxPostfix
    buffer += "}\n"
    return buffer


def generate_card_component(signatures: list[Signature]) -> str:
    buffer = ""
    buffer += AUTO_GENERATED_HEADER
    buffer += """
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
using MinionLib.Component.Interfaces;

namespace MinionLib.Component;

"""
    buffer += "public abstract partial class CardComponent\n{\n"
    for signature in signatures:
        (name, modifier, args, arg_names, return_type, default_impl) = signature
        XxxPrefix = f"""\
    public virtual {return_type} {name}Prefix({args}ComponentContext componentContext)
    {{
{default_impl}    }}
    
"""
        XxxPostfix = f"""\
    public virtual {return_type} {name}Postfix({args}ComponentContext componentContext)
    {{
{default_impl}    }}
    
"""
        buffer += XxxPrefix + XxxPostfix
    buffer += "}\n"
    return buffer


def generate_timing_enum(signatures: list[Signature]) -> str:
    buffer = ""
    buffer += AUTO_GENERATED_HEADER
    buffer += "namespace MinionLib.Component.Utils;\n\n"
    buffer += "public enum Timing\n"
    buffer += "{\n"
    for s in signatures:
        buffer += f"    {s.name},\n"
    buffer += "}\n"
    return buffer


def build_timing_ctx(args: list[str], timing: str) -> str:
    buffer = ""
    buffer += "var ctx = new OnTimingContext(\n"
    buffer += f"                Timing.{timing}{',' if args else ''}\n"
    for i in args:
        a = i[0].upper() + i[1:]
        buffer += f"                {a}: {i}{',' if i != args[-1] else ''}\n"
    buffer += "            );\n"
    return buffer


def generate_timing_component(signatures: list[Signature]) -> str:
    buffer = ""
    buffer += AUTO_GENERATED_HEADER
    buffer += """\
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
"""
    buffer += "namespace MinionLib.Component.Utils;\n\n"
    buffer += """\
public abstract partial class TimingCardComponent
{
"""
    for signature in signatures:
        (name, modifier, args, arg_names, return_type, default_impl) = signature

        buffer += f"""\
    public override {return_type} {name}Prefix({args}ComponentContext componentContext)
    {{
        if (Timings.Contains(Timing.{name}))
        {{
            {build_timing_ctx(list(filter((lambda x: x), arg_names.split(', '))), name)}
            {'return ' if return_type == 'Task' else ''}OnTimingPrefix(ctx);
        }}
{default_impl}
    }}
    public override {return_type} {name}Postfix({args}ComponentContext componentContext)
    {{
        if (Timings.Contains(Timing.{name}))
        {{
            {build_timing_ctx(list(filter((lambda x: x), arg_names.split(', '))), name)}
            {'return ' if return_type == 'Task' else ''}OnTimingPostfix(ctx);
        }}
{default_impl}
    }}
"""

    buffer += "}\n"
    return buffer


def parse_csharp_signature(line: str) -> Signature:
    # 正则表达式说明：
    # ^\s*                      : 匹配行首空白
    # (?P<modifier>\w+)         : 捕获组 modifier（匹配第一个单词，如 public/protected）
    # \s+(?:virtual\s+)?        : 匹配并忽略 virtual 关键字
    # (?:Task|void)\s+          : 匹配并忽略返回类型 (Task 或 void)
    # (?P<name>\w+)             : 捕获组 name（匹配方法名）
    # \((?P<args>.*?)\)         : 捕获组 args（匹配括号内的所有内容）
    pattern = r"^\s*(?P<modifier>\w+)\s+(?:virtual\s+)?(?P<return>Task|void)\s+(?P<name>\w+)\s*\((?P<args>.*?)\)"

    match = re.search(pattern, line.strip())
    if not match:
        raise ValueError(f"无法解析签名: {line}")

    modifier = match.group("modifier")
    return_type = match.group("return")
    name = match.group("name")
    args_str = match.group("args")

    # 提取参数名逻辑
    # 示例: "PlayerChoiceContext choiceContext, CardPlay cardPlay" -> ["choiceContext", "cardPlay"]
    arg_names_list = []
    if args_str.strip():
        # 按逗号分割各个参数
        individual_args = args_str.split(",")
        for arg in individual_args:
            parts = arg.strip().split(" ")
            # 最后一个单词通常是变量名 (e.g., "CardPlay cardPlay" -> "cardPlay")
            # 处理 "this Card card" 或 "ref int x" 的情况也适用
            if parts:
                arg_names_list.append(parts[-1])

    arg_names = ", ".join(arg_names_list + [""])

    return Signature(
        name=name,
        modifier=modifier,
        args=args_str + ", " if args_str else "",
        arg_names=arg_names,
        return_type=return_type,
        default_impl="        return Task.CompletedTask;\n" if return_type == "Task" else ""
    )


def main():
    with open(SCRIPT_DIR / 'methods_hooks.txt') as f:
        lines = f.readlines()
    signatures = [parse_csharp_signature(line) for line in lines]
    # s = set()
    # for signature in signatures:
    #     for i in signature.args.split(', '):
    #         ss = i.split(' ')
    #         if len(ss) < 2: continue
    #         a = ss[0]
    #         b = ss[1][0].upper() + ss[1][1:]
    #         s.add(f"{a} {b},")
    # print('\n'.join(s))

    with open(COMPONENT_DIR / "Partials" / "ComponentsCardModel_Hooks.cs", 'w') as f:
        code = generate_components_card(signatures)
        f.write(code)

    with open(COMPONENT_DIR / "Partials" / "ICardComponent_Hooks.cs", 'w') as f:
        code = generate_i_card_component(signatures)
        f.write(code)
    with open(COMPONENT_DIR / "Partials" / "CardComponent_Hooks.cs", 'w') as f:
        code = generate_card_component(signatures)
        f.write(code)

    with open(COMPONENT_DIR / "Utils" / "Timing.g.cs", 'w') as f:
        code = generate_timing_enum(signatures)
        f.write(code)

    with open(COMPONENT_DIR / "Utils" / "TimingCardComponent.g.cs", 'w') as f:
        code = generate_timing_component(signatures)
        f.write(code)


if __name__ == '__main__':
    main()
